# Generated by Django 3.2.13 on 2022-06-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='recipe',
            new_name='blog',
        ),
    ]
